export type Post = {slug:string;title:string;excerpt:string;category:string;date:string;read:string;image:string;body:string[]};
export const posts:Post[]=[
 {slug:"ai-marketing-that-earns-trust",title:"AI marketing that earns trust, not just attention",excerpt:"A practical framework for using AI while keeping your brand voice credible and human.",category:"AI Strategy",date:"August 6, 2026",read:"6 min read",image:"https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1400&q=85",body:["AI is most useful when it helps a team make better choices—not when it produces more noise.","Start with the moments where your customers need clarity. Then design a workflow that protects your point of view and makes room for human judgment.","A good system has three ingredients: a distinct source of insight, clear review standards, and a feedback loop from performance to creative decisions."]},
 {slug:"content-system-that-scales",title:"How to build a content system that scales with your business",excerpt:"Move beyond a frantic publishing calendar with a system built around useful ideas.",category:"Content Systems",date:"July 29, 2026",read:"5 min read",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=85",body:["Scale is not simply more posts. It is a dependable way to turn meaningful expertise into the right formats for the right people.","Map your core ideas first, then give each one a purpose across the customer journey."]},
 {slug:"automation-with-a-human-touch",title:"Marketing automation with a human touch",excerpt:"Where automation creates breathing room—and where a real person should still lead.",category:"Automation",date:"July 18, 2026",read:"4 min read",image:"https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1400&q=85",body:["Automation should remove friction, not warmth. The best journeys use it to be timely and relevant while leaving the important conversations human.","Audit repetitive moments, define your boundaries, and test every message in context."]},
 {slug:"metrics-that-move-decisions",title:"The marketing metrics that actually move decisions",excerpt:"A simpler way to turn busy dashboards into useful performance conversations.",category:"Analytics",date:"July 4, 2026",read:"5 min read",image:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=85",body:["Useful measurement begins with a decision. Before adding a number to a report, ask what the team will do differently after seeing it.","Focus reporting on the signals that connect activity to business outcomes."]},
 {slug:"positioning-in-an-ai-era",title:"Positioning in an AI era: why clarity matters more",excerpt:"When content is easy to produce, a clear point of view becomes your advantage.",category:"Brand Growth",date:"June 22, 2026",read:"6 min read",image:"https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1400&q=85",body:["AI has made execution faster. It has not made a brand's perspective less important.","The brands that stand out name a specific audience tension and show up with a useful, consistent answer."]},
 {slug:"social-growth-with-intent",title:"Social growth starts with intent, not volume",excerpt:"Build a social presence around the conversations worth having.",category:"Growth",date:"June 10, 2026",read:"4 min read",image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85",body:["More content is not always more connection. Find the themes where your expertise meets a real audience need.","Use a small set of repeatable formats, then learn from what sparks a response."]}
];
export const postBySlug=(slug:string)=>posts.find(p=>p.slug===slug);
