export type Service = { slug:string; title:string; summary:string; icon:string; for:string; challenges:string[]; deliverables:string[]; outcomes:string[]; faq:{q:string;a:string}[] };
export const services: Service[] = [
 {slug:"ai-marketing-strategy",title:"AI Marketing Strategy",icon:"✦",summary:"A practical roadmap that connects AI capability with your business goals.",for:"Teams ready to move from scattered experiments to a focused AI marketing plan.",challenges:["Unclear AI priorities","Disconnected channels","Slow decision-making"],deliverables:["Opportunity audit","90-day roadmap","Channel and measurement plan"],outcomes:["Sharper priorities","Better use of resources","A confident path to implementation"],faq:[{q:"Do we need a large tech stack?",a:"No. Recommendations are grounded in your existing capacity and the tools that genuinely fit."}]},
 {slug:"ai-powered-content-strategy",title:"AI-Powered Content Strategy",icon:"◌",summary:"Build useful, distinctive content systems that make every idea work harder.",for:"Brands that want consistent content without losing their human point of view.",challenges:["Inconsistent output","Content bottlenecks","Generic messaging"],deliverables:["Content pillars","AI-assisted workflow","Editorial calendar"],outcomes:["Faster creation","Stronger consistency","Clearer audience value"],faq:[{q:"Will it sound like us?",a:"Yes. Voice, review checkpoints, and original insight remain at the center of the system."}]},
 {slug:"social-media-growth-marketing",title:"Social Media & Growth Marketing",icon:"↗",summary:"Turn channel activity into an intentional, audience-led growth engine.",for:"Founders and marketing teams seeking sustainable social growth.",challenges:["Low engagement","Unclear channel roles","Inconsistent testing"],deliverables:["Channel strategy","Campaign concepts","Testing framework"],outcomes:["More focused effort","Better engagement","Learning that compounds"],faq:[{q:"Which channels do you cover?",a:"The work starts with where your audience and business goals are best served."}]},
 {slug:"marketing-automation",title:"Marketing Automation",icon:"⌘",summary:"Create thoughtful automations that save time and keep customer journeys moving.",for:"Teams with repeatable marketing work that is ready to be streamlined.",challenges:["Manual follow-ups","Fragmented journeys","Lost leads"],deliverables:["Journey mapping","Automation blueprint","Measurement checklist"],outcomes:["Less manual work","More timely touchpoints","Improved visibility"],faq:[{q:"Can this work with our existing tools?",a:"Yes. The blueprint is designed around your current stack before suggesting additions."}]},
 {slug:"brand-positioning-campaign-strategy",title:"Brand Positioning & Campaign Strategy",icon:"◎",summary:"Clarify your point of view, then translate it into campaigns people remember.",for:"Brands launching, evolving, or needing a clearer market story.",challenges:["Crowded category","Unclear message","Campaigns without cohesion"],deliverables:["Positioning workshop","Message architecture","Campaign platform"],outcomes:["Distinctive story","Aligned execution","Stronger relevance"],faq:[{q:"Is this suitable for a new brand?",a:"Absolutely. The process scales to an early-stage launch or an established repositioning."}]},
 {slug:"analytics-optimization-performance-insights",title:"Analytics, Optimization & Performance Insights",icon:"▣",summary:"Make marketing decisions with insight that is understandable, useful, and timely.",for:"Teams that have data but need better answers from it.",challenges:["Noisy reporting","Unclear KPIs","Slow optimization"],deliverables:["Measurement audit","KPI framework","Insight cadence"],outcomes:["Clearer decisions","Focused experiments","Stronger accountability"],faq:[{q:"Do you replace our analyst?",a:"No. This complements your team by making reporting and experimentation more actionable."}]}
];
export const serviceBySlug = (slug:string) => services.find(s => s.slug === slug);
